" get filesize, so we dont load plugins when editing very large files
" file is large from 10mb
let g:largeFileSize = 1024 * 1024 * 10
"let g:largeFile = getfsize(expand("<afile>")) > g:largeFileSize
let g:largeFile = getfsize(expand("%:p")) > g:largeFileSize

"load users config options
if filereadable(expand("~/.vim/config/config_manual.vim"))
  source ~/.vim/config/config_manual.vim
  "if user choose to load plugins load them
  if (g:load_plugins && !g:largeFile)
    if filereadable(expand("~/.vim/config/plug.vim"))
      source ~/.vim/config/plug.vim
    else
      filetype plugin indent on
    endif
  endif
endif
"load general vim settings
if filereadable(expand("~/.vim/config/general.vim"))
  source ~/.vim/config/general.vim
endif
"load general keybindings (does not include plugin keybindings)
if filereadable(expand("~/.vim/config/keybindings.vim"))
  source ~/.vim/config/keybindings.vim
endif
