if filereadable(expand("config/plug.vim"))
  source ~/.vim/config/plug.vim
endif
if filereadable(expand("config/general.vim"))
  source ~/.vim/config/general.vim
endif
if filereadable(expand("config/keybindings.vim"))
  source ~/.vim/config/keybindings.vim
endif


" load all files in dir 
"for f in split(glob('~/.vim/config/*.vim'), '\n')
"    exe 'source' f
"endfor

"for fpath in split(globpath('~/.vim/*.vim', '*.vim'), '\n')
"  exe 'source' fpath
"endfor

" source .vim files to suit configuration
